package:
  name: bluesky
  version: 0.3.1

source:
  git_url: https://github.com/NSLS-II/bluesky
  git_rev: v0.3.1

build:
  # Note that this will override the default build string with the Python
  # and NumPy versions
  number: 1
  string: py{{ py }}_{{ environ['CONDA_BUILD'] }}

requirements:
  build:
    - python >=3.4.3

  run:
    - python >=3.4.3
    - jsonschema
    - super_state_machine
    - numpy
    - metadatastore
    - filestore
    - matplotlib
    - prettytable
    - cycler
    - traitlets
    - historydict
    - lmfit

test:
  requires:
    - nslsii_dev_configuration
  imports:
    - bluesky
    - bluesky.examples

about:
  home: https://github.com/NSLS-II/bluesky
  license: BSD
