package:
  name: scikit-beam
  version: 0.0.6

source:
  git_url: https://github.com/scikit-beam/scikit-beam
  git_rev: v0.0.6

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - six
    - cython
  run:
    - python
    - numpy
    - scipy
    - six
    - xraylib [unix]
    - scikit-image
    - lmfit ==0.8.3

test:
  imports:
    - skbeam

about:
  home: http://scikit-beam.github.io/scikit-beam/
  license: 3-Clause BSD
